# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: BMCTTAutoRun@1
  inputs:
    HCIConnection: 'CW01:16196'
    UserID: 'PFHTXY0'
    Password: 'NewHope1'
    TestLocationPath: 'C:\Users\tyanish\BMC\DevX Workbench Workspaces\DevX_WB_v23.02.01_Workspace_Jan2024\TSA_TCTEST1\Tests\Scenarios'
    CLIInstallationPath: 'C:\WorkbenchCLI_v23.2.2'
    Configuration: 'LocalTTTConf'
    LocalTTTConfiguration: 'C:\Users\tyanish\BMC\DevX Workbench Workspaces\DevX_WB_v23.02.01_Workspace_Jan2024\TotalTestConfiguration'